const actividades_ciiu = [
    '0510 - Extracción de hulla (carbón de piedra). - 7',
    '0520 - Extracción de carbón lignito. - 7',
    '0610 - Extracción de petróleo crudo. - 7',
    '0620 - Extracción de gas natural. - 7',
    '0710 - Extracción de minerales de hierro. - 7',
    '0721 - Extracción de minerales de uranio y de torio. - 7',
    '0722 - Extracción de oro y otros metales preciosos. - 7',
    '0723 - Extracción de minerales de níquel. - 7',
    '0729 - Extracción de otros minerales metalíferos no ferrosos n.c.p. - 7',
    '0811 - Extracción de piedra, arena, arcillas comunes, yeso y anhidrita. - 6',
    '0812 - Extracción de arcillas de uso industrial, caliza, caolín y bentonitas. - 7',
    '0820 - Extracción de esmeraldas, piedras preciosas y semipreciosas. - 7',
    '0891 - Extracción de minerales para la fabricación de abonos y productos químicos. - 7',
    '0892 - Extracción de halita (sal). - 7',
    '0899 - Extracción de otros minerales no metálicos n.c.p. - 7',
    '0910 - Actividades de apoyo para la extracción de petróleo y de gas natural. - 7',
    '0990 - Actividades de apoyo para otras actividades de explotación de minas y canteras. - 7',
    '1011 - Procesamiento y conservación de carne y productos cárnicos. - 4',
    '1012 - Procesamiento y conservación de pescados, crustáceos y moluscos. - 4',
    '1020 - Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos. - 4',
    '1030 - Elaboración de aceites y grasas de origen vegetal y animal. - 4',
    '1040 - Elaboración de productos lácteos. - 4',
    '1051 - Elaboración de productos de molinería. - 4',
    '1052 - Elaboración de almidones y productos derivados del almidón. - 4',
    '1061 - Trilla de café. - 4',
    '1062 - Descafeinado, tostión y molienda del café. - 5',
    '1063 - Otros derivados del café. - 4',
    '1071 - Elaboración y refinación de azúcar. - 4',
    '1072 - Elaboración de panela. - 3',
    '1081 - Elaboración de productos de panadería. - 4',
    '1082 - Elaboración de cacao, chocolate y productos de confitería. - 4',
    '1083 - Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares. - 4',
    '1084 - Elaboración de comidas y platos preparados. - 4',
    '1089 - Elaboración de otros productos alimenticios n.c.p. - 4',
    '1090 - Elaboración de alimentos preparados para animales. - 5',
    '1101 - Destilación, rectificación y mezcla de bebidas alcohólicas. - 7',
    '1102 - Elaboración de bebidas fermentadas no destiladas. - 7',
    '1103 - Producción de malta, elaboración de cervezas y otras bebidas malteadas. - 6',
    '1104 - Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas. - 6',
    '1200 - Elaboración de productos de tabaco. - 7',
    '1311 - Preparación e hilatura de fibras textiles. - 4',
    '1312 - Tejeduría de productos textiles. - 4',
    '1313 - Acabado de productos textiles. - 4',
    '1391 - Fabricación de tejidos de punto y ganchillo. - 4',
    '4642 - Comercio al por mayor de prendas de vestir. - 6',
    '1393 - Fabricación de tapetes y alfombras para pisos. - 4',
    '1394 - Fabricación de cuerdas, cordeles, cables, bramantes y redes. - 4',
    '1399 - Fabricación de otros artículos textiles n.c.p. - 4',
    '4771 - Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados. - 6',
    '1420 - Fabricación de artículos de piel. - 4',
    '1430 - Fabricación de artículos de punto y ganchillo. - 2',
    '1511 - Curtido y recurtido de cueros; recurtido y teñido de pieles. - 3',
    '1512 - Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería. - 3',
    '1513 - Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales. - 3',
    '1521 - Fabricación de calzado de cuero y piel, con cualquier tipo de suela. - 3',
    '1522 - Fabricación de otros tipos de calzado, excepto calzado de cuero y piel. - 3',
    '1523 - Fabricación de partes del calzado. - 3',
    '1610 - Aserrado, acepillado e impregnación de la madera. - 4',
    '1620 - Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles. - 4',
    '1630 - Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción. - 4',
    '1640 - Fabricación de recipientes de madera. - 4',
    '1690 - Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería. - 4',
    '1701 - Fabricación de pulpas (pastas) celulósicas; papel y cartón. - 7',
    '1702 - Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón. - 7',
    '1709 - Fabricación de otros artículos de papel y cartón. - 4',
    '1811 - Actividades de impresión. - 4',
    '1812 - Actividades de servicios relacionados con la impresión. - 4',
    '1820 - Producción de copias a partir de grabaciones originales. - 4',
    '1910 - Fabricación de productos de hornos de coque. - 4',
    '1921 - Fabricación de productos de la refinación del petróleo. - 7',
    '1922 - Actividad de mezcla de combustibles. - 7',
    '2011 - Fabricación de sustancias y productos químicos básicos. - 7',
    '2012 - Fabricación de abonos y compuestos inorgánicos nitrogenados. - 7',
    '2013 - Fabricación de plásticos en formas primarias. - 4',
    '2014 - Fabricación de caucho sintético en formas primarias. - 4',
    '2021 - Fabricación de plaguicidas y otros productos químicos de uso agropecuario. - 4',
    '2022 - Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas. - 4',
    '2023 - Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador. - 4',
    '2029 - Fabricación de otros productos químicos n.c.p. - 4',
    '2030 - Fabricación de fibras sintéticas y artificiales. - 5',
    '2100 - Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico. - 4',
    '2211 - Fabricación de llantas y neumáticos de caucho - 4',
    '2212 - Reencauche de llantas usadas - 4',
    '2219 - Fabricación de formas básicas de caucho y otros productos de caucho n.c.p. - 4',
    '2221 - Fabricación de formas básicas de plástico. - 6',
    '2229 - Fabricación de artículos de plástico n.c.p. - 6',
    '2310 - Fabricación de vidrio y productos de vidrio. - 5',
    '2391 - Fabricación de productos refractarios. - 4',
    '2392 - Fabricación de materiales de arcilla para la construcción. - 4',
    '2393 - Fabricación de otros productos de cerámica y porcelana. - 4',
    '2394 - Fabricación de cemento, cal y yeso. - 4',
    '2395 - Fabricación de artículos de hormigón, cemento y yeso. - 4',
    '2396 - Corte, tallado y acabado de la piedra. - 4',
    '2399 - Fabricación de otros productos minerales no metálicos n.c.p. - 4',
    '2410 - Industrias básicas de hierro y de acero. - 5',
    '2421 - Industrias básicas de metales preciosos. - 5',
    '2429 - Industrias básicas de otros metales no ferrosos. - 5',
    '2431 - Fundición de hierro y de acero. - 5',
    '2432 - Fundición de metales no ferrosos. - 5',
    '2511 - Fabricación de productos metálicos para uso estructural. - 5',
    '2512 - Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías. - 5',
    '2513 - Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central. - 5',
    '2520 - Fabricación de armas y municiones. - 7',
    '2591 - Forja, prensado, estampado y laminado de metal; pulvimetalurgia. - 4',
    '2592 - Tratamiento y revestimiento de metales; mecanizado. - 4',
    '2593 - Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería. - 4',
    '2599 - Fabricación de otros productos elaborados de metal n.c.p. - 4',
    '2610 - Fabricación de componentes y tableros electrónicos. - 4',
    '2620 - Fabricación de computadoras y de equipo periférico. - 4',
    '2630 - Fabricación de equipos de comunicación. - 4',
    '2640 - Fabricación de aparatos electrónicos de consumo. - 4',
    '2651 - Fabricación de equipo de medición, prueba, navegación y control. - 4',
    '2652 - Fabricación de relojes. - 4',
    '2660 - Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico. - 4',
    '2670 - Fabricación de instrumentos ópticos y equipo fotográfico. - 4',
    '2680 - Fabricación de medios magnéticos y ópticos para almacenamiento de datos. - 4',
    '2711 - Fabricación de motores, generadores y transformadores eléctricos. - 4',
    '2712 - Fabricación de aparatos de distribución y control de la energía eléctrica. - 4',
    '2720 - Fabricación de pilas, baterías y acumuladores eléctricos. - 4',
    '2731 - Fabricación de hilos y cables eléctricos y de fibra óptica. - 4',
    '2732 - Fabricación de dispositivos de cableado. - 4',
    '2740 - Fabricación de equipos eléctricos de iluminación. - 4',
    '2750 - Fabricación de aparatos de uso doméstico. - 4',
    '2790 - Fabricación de otros tipos de equipo eléctrico n.c.p. - 4',
    '2811 - Fabricación de motores, turbinas, y partes para motores de combustión interna. - 4',
    '2812 - Fabricación de equipos de potencia hidráulica y neumática. - 4',
    '2813 - Fabricación de otras bombas, compresores, grifos y válvulas. - 4',
    '2814 - Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión. - 4',
    '2815 - Fabricación de hornos, hogares y quemadores industriales. - 4',
    '2816 - Fabricación de equipo de elevación y manipulación. - 4',
    '2817 - Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico). - 4',
    '2818 - Fabricación de herramientas manuales con motor. - 4',
    '2819 - Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p. - 4',
    '2821 - Fabricación de maquinaria agropecuaria y forestal. - 3',
    '2822 - Fabricación de máquinas formadoras de metal y de máquinas herramienta. - 3',
    '2823 - Fabricación de maquinaria para la metalurgia. - 3',
    '2824 - Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción. - 3',
    '2825 - Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco. - 3',
    '4782 - Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles. - 8',
    '2829 - Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p. - 3',
    '2910 - Fabricación de vehículos automotores y sus motores. - 4',
    '2920 - Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques. - 4',
    '2930 - Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores. - 4',
    '3091 - Fabricación de motocicletas. - 4',
    '3092 - Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad. - 4',
    '3099 - Fabricación de otros tipos de equipo de transporte n.c.p. - 4',
    '3110 - Fabricación de muebles. - 3',
    '3120 - Fabricación de colchones y somieres. - 3',
    '3210 - Fabricación de joyas, bisutería y artículos conexos. - 2',
    '3220 - Fabricación de instrumentos musicales. - 3',
    '3230 - Fabricación de artículos y equipo para la práctica del deporte. - 4',
    '3240 - Fabricación de juegos, juguetes y rompecabezas. - 4',
    '3250 - Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario). - 4',
    '3290 - Otras industrias manufactureras n.c.p. - 4',
    '3311 - Mantenimiento y reparación especializado de productos elaborados en metal. - 4',
    '3312 - Mantenimiento y reparación especializado de maquinaria y equipo. - 4',
    '3313 - Mantenimiento y reparación especializado de equipo electrónico y óptico. - 4',
    '3314 - Mantenimiento y reparación especializado de equipo eléctrico. - 4',
    '3315 - Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas. - 4',
    '3319 - Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p. - 4',
    '3320 - Instalación especializada de maquinaria y equipo industrial. - 4',
    '3511 - Generación de energía eléctrica. - 7',
    '3512 - Transmisión de energía eléctrica. - 7',
    '3513 - Distribución de energía eléctrica. - 7',
    '3514 - Comercialización de energía eléctrica. - 10',
    '3520 - Producción de gas; distribución de combustibles gaseosos por tuberías. - 7',
    '3530 - Suministro de vapor y aire acondicionado. - 7',
    '3600 - Captación, tratamiento y distribución de agua. - 10',
    '3700 - Evacuación y tratamiento de aguas residuales. - 10',
    '3811 - Recolección de desechos no peligrosos. - 10',
    '3812 - Recolección de desechos peligrosos. - 10',
    '3821 - Tratamiento y disposición de desechos no peligrosos. - 10',
    '3822 - Tratamiento y disposición de desechos peligrosos. - 10',
    '3830 - Recuperación de materiales. - 5',
    '3900 - Actividades de saneamiento ambiental y otros servicios de gestión de desechos. - 5',
    '4111 - Construcción de edificios residenciales. - 7',
    '4112 - Construcción de edificios no residenciales. - 7',
    '4210 - Construcción de carreteras y vías de ferrocarril. - 7',
    '4220 - Construcción de proyectos de servicio público. - 7',
    '4290 - Construcción de otras obras de ingeniería civil. - 7',
    '4311 - Demolición. - 10',
    '4312 - Preparación del terreno. - 10',
    '4321 - Instalaciones eléctricas. - 8',
    '4322 - Instalaciones de fontanería, calefacción y aire acondicionado. - 8',
    '4329 - Otras instalaciones especializadas. - 8',
    '4330 - Terminación y acabado de edificios y obras de ingeniería civil. - 7',
    '4390 - Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil. - 7',
    '4511 - Comercio de vehículos automotores nuevos. - 9',
    '4512 - Comercio de vehículos automotores usados. - 8',
    '4520 - Mantenimiento y reparación de vehículos automotores. - 5',
    '4530 - Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores. - 7',
    '4541 - Comercio de motocicletas y de sus partes, piezas y accesorios. - 6',
    '4542 - Mantenimiento y reparación de motocicletas y de sus partes y piezas. - 3',
    '4610 - Comercio al por mayor a cambio de una retribución o por contrata. - 7',
    '4620 - Comercio al por mayor de materias primas agropecuarias; animales vivos. - 5',
    '4631 - Comercio al por mayor de productos alimenticios. - 6',
    '4632 - Comercio al por mayor de bebidas y tabaco. - 8',
    '4641 - Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico. - 6',
    '1392 - Confección de artículos con materiales textiles, excepto prendas de vestir. - 4',
    '4643 - Comercio al por mayor de calzado. - 6',
    '4644 - Comercio al por mayor de aparatos y equipo de uso doméstico. - 6',
    '4645 - Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador. - 6',
    '4649 - Comercio al por mayor de otros utensilios domésticos n.c.p. - 6',
    '4651 - Comercio al por mayor de computadores, equipo periférico y programas de informática. - 5',
    '4652 - Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones. - 5',
    '4653 - Comercio al por mayor de maquinaria y equipo agropecuarios. - 6',
    '4659 - Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p. - 7',
    '4661 - Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos. - 4',
    '4662 - Comercio al por mayor de metales y productos metalíferos. - 4',
    '4663 - Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción. - 7',
    '4664 - Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario. - 7',
    '4665 - Comercio al por mayor de desperdicios, desechos y chatarra. - 5',
    '4669 - Comercio al por mayor de otros productos n.c.p. - 7',
    '4690 - Comercio al por mayor no especializado. - 10',
    '4711 - Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco. - 7',
    '4719 - Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco. - 5',
    '4721 - Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados. - 7',
    '4722 - Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados. - 4',
    '4723 - Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados. - 4',
    '4724 - Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados. - 8',
    '4729 - Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados. - 7',
    '4731 - Comercio al por menor de combustible para automotores. - 7',
    '4732 - Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores. - 7',
    '4741 - Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados. - 5',
    '4742 - Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados. - 6',
    '4751 - Comercio al por menor de productos textiles en establecimientos especializados. - 6',
    '4752 - Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados. - 7',
    '4753 - Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados. - 7',
    '4754 - Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación. - 6',
    '4755 - Comercio al por menor de artículos y utensilios de uso doméstico. - 6',
    '4759 - Comercio al por menor de otros artículos domésticos en establecimientos especializados. - 6',
    '4761 - Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados. - 6',
    '4762 - Comercio al por menor de artículos deportivos, en establecimientos especializados. - 6',
    '4769 - Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados. - 6',
    '1410 - Confección de prendas de vestir, excepto prendas de piel. - 2',
    '4772 - Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados. - 6',
    '4773 - Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados. - 6',
    '4774 - Comercio al por menor de otros productos nuevos en establecimientos especializados. - 6',
    '4775 - Comercio al por menor de artículos de segunda mano. - 10',
    '4781 - Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles. - 8',
    '2826 - Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros. - 3',
    '4789 - Comercio al por menor de otros productos en puestos de venta móviles. - 8',
    '4791 - Comercio al por menor realizado a través de internet. - 4',
    '4792 - Comercio al por menor realizado a través de casas de venta o por correo. - 4',
    '4799 - Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados. - 4',
    '4911 - Transporte férreo de pasajeros. - 4',
    '4912 - Transporte férreo de carga. - 4',
    '4921 - Transporte de pasajeros. - 4',
    '4922 - Transporte mixto. - 4',
    '4923 - Transporte de carga por carretera. - 4',
    '4930 - Transporte por tuberías. - 4',
    '5210 - Almacenamiento y depósito. - 5',
    '5221 - Actividades de estaciones, vías y servicios complementarios para el transporte terrestre. - 4',
    '5222 - Actividades de puertos y servicios complementarios para el transporte acuático. - 4',
    '5223 - Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo. - 4',
    '5224 - Manipulación de carga. - 4',
    '5229 - Otras actividades complementarias al transporte. - 4',
    '5310 - Actividades postales nacionales. - 4',
    '5320 - Actividades de mensajería. - 4',
    '5511 - Alojamiento en hoteles. - 4',
    '5512 - Alojamiento en aparta hoteles. - 4',
    '5513 - Alojamiento en centros vacacionales. - 4',
    '5514 - Alojamiento rural. - 4',
    '5519 - Otros tipos de alojamientos para visitantes. - 4',
    '5520 - Actividades de zonas de camping y parques para vehículos recreacionales. - 4',
    '5530 - Servicio por horas - 4',
    '5590 - Otros tipos de alojamiento n.c.p. - 4',
    '5611 - Expendio a la mesa de comidas preparadas. - 4',
    '5612 - Expendio por autoservicio de comidas preparadas. - 4',
    '5613 - Expendio de comidas preparadas en cafeterias. - 4',
    '5619 - Otros tipos de expendio de comidas preparadas n.c.p. - 4',
    '5621 - Catering para eventos. - 4',
    '5629 - Actividades de otros servicios de comidas. - 4',
    '5630 - Expendio de bebidas alcohólicas para el consumo dentro del establecimiento. - 8',
    '5811 - Edición de libros. - 3',
    '5812 - Edición de directorios y listas de correo. - 3',
    '5813 - Edición de periódicos, revistas y otras publicaciones periódicas. - 3',
    '5819 - Otros trabajos de edición. - 3',
    '5820 - Edición de programas de informática (software). - 3',
    '5911 - Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión. - 3',
    '5912 - Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión. - 3',
    '5913 - Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión. - 3',
    '5914 - Actividades de exhibición de películas cinematográficas y videos. - 3',
    '5920 - Actividades de grabación de sonido y edición de música. - 3',
    '6010 - Actividades de programación y transmisión en el servicio de radiodifusión sonora. - 4',
    '6020 - Actividades de programación y transmisión de televisión. - 10',
    '6110 - Actividades de telecomunicaciones alámbricas. - 10',
    '6120 - Actividades de telecomunicaciones inalámbricas. - 10',
    '6130 - Actividades de telecomunicación satelital. - 10',
    '6190 - Otras actividades de telecomunicaciones. - 9',
    '6201 - Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas). - 4',
    '6202 - Actividades de consultoría informática y actividades de Administración de instalaciones informáticas. - 4',
    '6209 - Otras actividades de tecnologías de información y actividades de servicios informáticos. - 4',
    '6311 - Procesamiento de datos, alojamiento (hosting) y actividades relacionadas. - 4',
    '6312 - Portales web. - 4',
    '6391 - Actividades de agencias de noticias. - 3',
    '6399 - Otras actividades de servicio de información n.c.p. - 3',
    '6411 - Banco Central. - 4',
    '6412 - Bancos comerciales. - 4',
    '6421 - Actividades de las corporaciones financieras. - 4',
    '6422 - Actividades de las compañías de financiamiento. - 4',
    '6423 - Banca de segundo piso. - 4',
    '6424 - Actividades de las cooperativas financieras. - 4',
    '6431 - Fideicomisos, fondos y entidades financieras similares. - 4',
    '6432 - Fondos de cesantías. - 4',
    '6491 - Leasing financiero (arrendamiento financiero). - 4',
    '6492 - Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario. - 4',
    '6493 - Actividades de compra de cartera o factoring. - 4',
    '6494 - Otras actividades de distribución de fondos. - 4',
    '6495 - Instituciones especiales oficiales. - 4',
    '6499 - Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p. - 4',
    '6511 - Seguros generales. - 8',
    '6512 - Seguros de vida. - 8',
    '6513 - Reaseguros. - 8',
    '6514 - Capitalización. - 8',
    '6611 - Administración de mercados financieros. - 4',
    '6612 - Corretaje de valores y de contratos de productos básicos. - 4',
    '6613 - Otras actividades relacionadas con el mercado de valores. - 4',
    '6614 - Actividades de las casas de cambio. - 8',
    '6615 - Actividades de los profesionales de compra y venta de divisas. - 4',
    '6619 - Otras actividades auxiliares de las actividades de servicios financieros n.c.p. - 4',
    '6621 - Actividades de agentes y corredores de seguros - 4',
    '6629 - Evaluación de riesgos y daños, y otras actividades de servicios auxiliares - 4',
    '6630 - Actividades de Administración de fondos. - 4',
    '6810 - Actividades inmobiliarias realizadas con bienes propios o arrendados. - 6',
    '6820 - Actividades inmobiliarias realizadas a cambio de una retribución o por contrata. - 5',
    '6910 - Actividades jurídicas. - 5',
    '6920 - Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria. - 5',
    '7010 - Actividades de Administración empresarial. - 5',
    '7020 - Actividades de consultaría de gestión. - 5',
    '7110 - Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica. - 5',
    '7120 - Ensayos y análisis técnicos. - 5',
    '7210 - Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería. - No genera',
    '7220 - Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades. - No genera',
    '7310 - Publicidad. - 8',
    '7320 - Estudios de mercado y realización de encuestas de opinión pública. - 5',
    '7410 - Actividades especializadas de diseño. - 5',
    '7420 - Actividades de fotografía. - 5',
    '7490 - Otras actividades profesionales, científicas y técnicas n.c.p. - 5',
    '7500 - Actividades veterinarias. - 5',
    '7710 - Alquiler y arrendamiento de vehículos automotores. - 4',
    '7721 - Alquiler y arrendamiento de equipo recreativo y deportivo. - 0',
    '7722 - Alquiler de videos y discos. - 6',
    '7729 - Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p. - 3',
    '7730 - Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p. - 7',
    '7740 - Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor. - 0',
    '7810 - Actividades de agencias de empleo. - 8',
    '7820 - Actividades de agencias de empleo temporal. - 8',
    '7830 - Otras actividades de suministro de recurso humano. - 8',
    '7911 - Actividades de las agencias de viaje. - 4',
    '7912 - Actividades de operadores turísticos. - 4',
    '7990 - Otros servicios de reserva y actividades relacionadas. - 4',
    '8010 - Actividades de seguridad privada. - 6',
    '8020 - Actividades de servicios de sistemas de seguridad. - 6',
    '8030 - Actividades de detectives e investigadores privados. - 6',
    '8110 - Actividades combinadas de apoyo a instalaciones. - 6',
    '8121 - Limpieza general interior de edificios. - 4',
    '8129 - Otras actividades de limpieza de edificios e instalaciones industriales. - 4',
    '8130 - Actividades de paisajismo y servicios de mantenimiento conexos. - 4',
    '8211 - Actividades combinadas de servicios administrativos de oficina. - 6',
    '8219 - Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina. - 6',
    '8220 - Actividades de centros de llamadas (Call center). - 3',
    '8230 - Organización de convenciones y eventos comerciales. - 4',
    '8291 - Actividades de agencias de cobranza y oficinas de calificación crediticia. - 4',
    '8292 - Actividades de envase y empaque. - 3',
    '8299 - Otras actividades de servicio de apoyo a las empresas n.c.p. - 6',
    '8511 - Educación de la primera infancia. - 2',
    '8512 - Educación preescolar. - 2',
    '8513 - Educación básica primaria. - 2',
    '8521 - Educación básica secundaria. - 2',
    '8522 - Educación media académica. - 2',
    '8523 - Educación media técnica y de formación laboral. - 2',
    '8530 - Establecimientos que combinan diferentes niveles de educación. - 2',
    '8541 - Educación técnica profesional. - 2',
    '8542 - Educación tecnológica. - 2',
    '8543 - Educación de instituciones universitarias o de escuelas tecnológicas. - 2',
    '8544 - Educación de universidades. - 2',
    '8551 - Formación académica no formal. - 8',
    '8559 - Otros tipos de educación n.c.p. - 8',
    '8560 - Actividades de apoyo a la educación. - 8',
    '8610 - Actividades de hospitales y clínicas, con internación. - 4',
    '8621 - Actividades de la práctica médica, sin internación. - 4',
    '8622 - Actividades de la práctica odontológica. - 4',
    '8691 - Actividades de apoyo diagnóstico. - 4',
    '8692 - Actividades de apoyo terapéutico. - 4',
    '8699 - Otras actividades de atención de la salud humana. - 4',
    '8710 - Actividades de atención residencial medicalizada de tipo general. - 4',
    '8720 - Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas. - 3',
    '8730 - Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas. - 3',
    '8790 - Otras actividades de atención en instituciones con alojamiento - 3',
    '8810 - Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas. - 3',
    '8890 - Otras actividades de asistencia social sin alojamiento. - 3',
    '9200 - Actividades de juegos de azar y apuestas. - 9',
    '9311 - Gestión de instalaciones deportivas. - 3',
    '9312 - Actividades de clubes deportivos. - 0',
    '9319 - Otras actividades deportivas. - 0',
    '9321 - Actividades de parques de atracciones y parques temáticos. - 4',
    '9329 - Otras actividades recreativas y de esparcimiento n.c.p. - 4',
    '9411 - Actividades de asociaciones empresariales y de empleadores - 0',
    '9412 - Actividades de asociaciones profesionales - 0',
    '9420 - Actividades de sindicatos de empleados. - 0',
    '9492 - Actividades de asociaciones políticas. - 0',
    '9499 - Actividades de otras asociaciones n.c.p. - 8',
    '9511 - Mantenimiento y reparación de computadores y de equipo periférico. - 6',
    '9512 - Mantenimiento y reparación de equipos de comunicación. - 6',
    '9521 - Mantenimiento y reparación de aparatos electrónicos de consumo. - 5',
    '9522 - Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería. - 5',
    '9523 - Reparación de calzado y artículos de cuero. - 5',
    '9524 - Reparación de muebles y accesorios para el hogar. - 5',
    '9529 - Mantenimiento y reparación de otros efectos personales y enseres domésticos. - 5',
    '9601 - Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel. - 4',
    '9602 - Peluquería y otros tratamientos de belleza. - 4',
    '9603 - Pompas fúnebres y actividades relacionadas. - 8',
    '9609 - Otras actividades de servicios personales n.c.p. - 5',
    '0090 - Rentistas de Capital, solo para personas naturales. - 5',
];

export default actividades_ciiu;